### ISSUE TITLE
Is spyplugins/__init__.py necessary?

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyplugins.ui.example#1]
After reviewing spyder-ide/spyder#2565, I'd say it is not necessary because it's provided by Spyder itself.

**Comment by ccordoba12** [comment]
Besides, if you run `pip uninstall spyplugins.ui.example`, it will remove it. Would not that cause problems for the other (installed) plugins?

**Comment by goanpeca** [comment]
We need for compatibility issues... (python 2.7...) [Implicit namespace ](https://www.python.org/dev/peps/pep-0420/)

I have to check with a pip installed package to check what you ask, but doing `python setup.py install` will not add anythin gnew to spyplugins, but leave it in another folder... like

`conda_manager-0.1.2-py2.7.egg` so that removing this package will not affect `spyplugins` installed by spyder (which does reside as a top level thing in site-packages)

**Comment by Nodd** [comment]
You also need it in case of the plugin being installed before spyder. It could happen when reinstalling spyder.

**Comment by goanpeca** [comment]
@Nodd where can I leave some msgs? gitter?, email?

**Comment by Nodd** [comment]
Messages on gitter have a tendancy to be buried quite fast, so email is better.

**Comment by ccordoba12** [comment]
@goanpeca, so closing  this one or not?

**Comment by goanpeca** [comment]
Yes it is necessary because of the reasons explained above

**Comment by ccordoba12** [comment]
Ok, no prob ;-)

Please don't forget to rename our plugins to the names we agreed on our meeting.

**Comment by goanpeca** [comment]
Yes I will when I am back in Bucara, I am in Medallo right now :p

**Comment by ccordoba12** [comment]
Ok
